<?php 

$title = $this->titulo;
$this->headTitle($title);

$form = $this->form;
//$form->setAttribute('action', $this->url());
$form->setAttribute('class', 'form-horizontal form-label-left');

$isEdit = (!empty($this->isEdit) ? true : false);
$btnDsc = (!empty($isEdit) ? 'Grabar' : 'Grabar');
$campos = $this->campos;
$descripciones = $this->camposDescripcion;

foreach ($campos as $keyField => $field) {
    $showField = false;
    
    if ((((empty($field['AI']) || $field['AI'] == 0) && !$isEdit) || $isEdit) && empty($field['FK'])) {
        $form->add([
            'name' => $keyField,
            'type' => 'text',
            'attributes' => [
               'class' => 'form-control col-md-7 col-xs-12 ' . (!empty($field['DATE'])? 'date-picker' : ''),
                'maxlength' => (!empty($field['LENGHT']) ? $field['LENGHT'] : null),
                'required' => 'required',
                'value' => (!empty($this->defaultValue[$keyField])? $this->defaultValue[$keyField]: ''),
                'readonly' => (!empty($field['PK'])? $field['PK']: ''),
            ],
            'options' => [
                'label' => $descripciones[$keyField],
                'label_attributes' => array(
                    'class' => 'control-label col-md-3 col-sm-3 col-xs-12',
                ),
            ],
        ]);
        
        $showField = true;
    }

    if (!empty($field['FK'])) {
        $form->add([
            'name' => $keyField,
            'type' => 'select',
            'attributes' => [
               'class' => 'form-control col-md-7 col-xs-12',
                'required' => 'required',
                'value' => (!empty($this->defaultValue[$keyField])? $this->defaultValue[$keyField]: ''),
            ],
            'options' => [
                'label' => $descripciones[$keyField],
                'label_attributes' => array(
                    'class' => 'control-label col-md-3 col-sm-3 col-xs-12',
                ),
                'value_options' => (!empty($field['FUNC']) && !empty($this->fk[$field['FUNC']]) ? $this->fk[$field['FUNC']] : [])
            ],
        ]);
        
        $showField = true;
    }
    
    if ($showField) {
        $formFields[] = $form->get($keyField);
    }
}

$element = new \Zend\Form\Element('reset');
$element->setAttribute('class', 'btn btn-primary');
$element->setAttribute('value', 'Cancelar');

$form->add($element);
$form->add([
    'type' => 'submit',
    'name' => 'submit',
    'attributes' => [
        'class' => 'btn btn-success',
        'value' => $btnDsc,
    ],
]);
$submit = $form->get('submit');
$reset = $form->get('reset');

$form->prepare();
?>
<div class="row">

<div class="page-title col-md-12 col-sm-12 col-xs-12">
    <div class="title_left">
        <h3><?= $this->escapeHtml($title); ?></h3>
    </div>

    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar ...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">Ir!</button>
                </span>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Agregar</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br>
        <?= $this->form()->openTag($form); ?>
        <?php foreach ($formFields as $field): ?>
        <div class="form-group">
            <?= $this->formLabel($field) ?>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <?= $this->formElement($field) ?>
            </div>
            <?= $this->formElementErrors()->render($field, ['class' => 'help-block']) ?>
        </div>
        <?php endforeach; ?>
        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <?= $this->formSubmit($submit); ?>
              <?= $this->formReset($reset); ?>
            </div>
        </div>
        <?php
        echo $this->form()->closeTag();
        ?>
      </div>
    </div>
  </div>
</div>
<?php    
    $this->inlineScript()->captureStart();
    echo "
        var salones = " . json_encode($this->salones) . ";
        var ctas_bancarias = " . json_encode($this->ctasbancarias) . ";
            
        $(\"select[name='colegio_id']\").change(function(){
            var prinId = $(this).val();
            var data = salones[prinId];
          
            $(\"select[name='salon_id']\").html('');
            $.each(data, function(id, value) {
                $(\"select[name='salon_id']\").append($(\"<option />\").val(id).text(value));
            });
        });
        
        $(\"select[name='moneda_id']\").change(function(){
            var prinId = $(this).val();
            var data = ctas_bancarias[prinId];
          
            $(\"select[name='cta_bancaria_id']\").html('');
            $.each(data, function(id, value) {
                $(\"select[name='cta_bancaria_id']\").append($(\"<option />\").val(id).text(value));
            });
        });
        
        $(\"select[name='colegio_id']\").change();
        $(\"select[name='moneda_id']\").change();
    ";
    $this->inlineScript()->captureEnd();
?>