<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        
        <?php // $this->headTitle('SisRes - Sistema de Reservas')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('vendors/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('vendors/nprogress/nprogress.css'))
                        ->prependStylesheet($this->basePath('vendors/bootstrap-daterangepicker/daterangepicker.css'))
                        ->prependStylesheet($this->basePath('build/css/custom.min.css'))
                        ->prependStylesheet($this->basePath('vendors/bootstrap/dist/css/bootstrap.min.css'))

        ?>
    </head>

    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="index.html" class="site_title"><i class="fa fa-globe"></i> <span><?= \Negocio\Configuracion::Empresa ?></span></a>
                        </div>

                        <div class="clearfix"></div>

                        <!-- menu profile quick info -->
                        <div class="profile clearfix">
                            <div class="profile_pic">
                                <img src="/images/img.jpg" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Welcome,</span>
                                <h2>John Doe</h2>
                            </div>
                        </div>
                        <!-- /menu profile quick info -->

                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section">
                                <h3>General</h3>
                                <ul class="nav side-menu">
                                    <li><a href="/cobranza"><i class="fa fa-home"></i> Home</a>
                                    </li>
                                    <li><a><i class="fa fa-edit"></i> Mantenimiento <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="/cobranza/moneda">Moneda</a></li>
                                            <li><a href="/cobranza/banco">Banco</a></li>
                                            <li><a href="/cobranza/cta-bancaria">Cta Bancaria</a></li>
                                            <li><a href="/cobranza/colegio">Colegio</a></li>
                                            <li><a href="/cobranza/tipo-documento">Documento Pax</a></li>
                                            <li><a href="/cobranza/nacionalidad">Nacionalidad</a></li>
                                            <li><a href="/cobranza/tipo-pax">Tipo Pax</a></li>
                                            <li><a href="/cobranza/pasajero">Pasajero</a></li>
                                            <li><a href="/cobranza/paquete-turistico">Paquete Turístico</a></li>
                                        </ul>
                                    </li
                                </ul>
                            </div>

                        </div>
                        <!-- /sidebar menu -->

                        <!-- /menu footer buttons -->
                        <div class="sidebar-footer hidden-small">
                            <a data-toggle="tooltip" data-placement="top" title="Settings">
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Lock">
                                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Logout">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            </a>
                        </div>
                        <!-- /menu footer buttons -->
                    </div>
                </div>

                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <nav>
                            <div class="nav toggle">
                                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                            </div>

                            <ul class="nav navbar-nav navbar-right">
                                <li class="">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <img src="/images/img.jpg" alt="">John Doe
                                        <span class=" fa fa-angle-down"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                                        <li><a href="javascript:;"> Profile</a></li>
                                        <li>
                                            <a href="javascript:;">
                                                <span class="badge bg-red pull-right">50%</span>
                                                <span>Settings</span>
                                            </a>
                                        </li>
                                        <li><a href="javascript:;">Help</a></li>
                                        <li><a href="/cobranza/logout"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                    </ul>
                                </li>

                                <li role="presentation" class="dropdown">
                                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fa fa-envelope-o"></i>
                                        <span class="badge bg-green">6</span>
                                    </a>
                                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                        <li>
                                            <a>
                                                <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a>
                                                <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a>
                                                <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a>
                                                <span class="image"><img src="/images/img.jpg" alt="Profile Image" /></span>
                                                <span>
                                                    <span>John Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <div class="text-center">
                                                <a>
                                                    <strong>See All Alerts</strong>
                                                    <i class="fa fa-angle-right"></i>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- /top navigation -->

                <!-- page content -->
                <div class="right_col" role="main">
                    <?= $this->content ?>
                </div>
                <!-- /page content -->

                <!-- footer content -->
                <footer>
                    <div class="pull-right">
                        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
                    </div>
                    <div class="clearfix"></div>
                </footer>
                <!-- /footer content -->
            </div>
        </div>
        <!-- Scripts -->
        <?=
                $this->headScript()
                ->appendFile($this->basePath('vendors/jquery/dist/jquery.min.js'))
                ->appendFile($this->basePath('vendors/bootstrap/dist/js/bootstrap.min.js'))
                ->appendFile($this->basePath('vendors/fastclick/lib/fastclick.js'))
                ->appendFile($this->basePath('vendors/nprogress/nprogress.js'))
                ->appendFile($this->basePath('vendors/Chart.js/dist/Chart.min.js'))
                ->appendFile($this->basePath('vendors/jquery-sparkline/dist/jquery.sparkline.min.js'))
                ->appendFile($this->basePath('vendors/Flot/jquery.flot.js'))
                ->appendFile($this->basePath('vendors/Flot/jquery.flot.pie.js'))
                ->appendFile($this->basePath('vendors/Flot/jquery.flot.time.js'))
                ->appendFile($this->basePath('vendors/Flot/jquery.flot.stack.js'))
                ->appendFile($this->basePath('vendors/Flot/jquery.flot.resize.js'))
                ->appendFile($this->basePath('vendors/flot.orderbars/js/jquery.flot.orderBars.js'))
                ->appendFile($this->basePath('vendors/flot-spline/js/jquery.flot.spline.min.js'))
                ->appendFile($this->basePath('vendors/flot.curvedlines/curvedLines.js'))
                ->appendFile($this->basePath('vendors/DateJS/build/date.js'))
                ->appendFile($this->basePath('vendors/moment/min/moment.min.js'))
                ->appendFile($this->basePath('vendors/bootstrap-daterangepicker/daterangepicker.js'))
                ->appendFile($this->basePath('build/js/custom.min.js'))
        ?>
        <?= $this->inlineScript() ?>

    </body>
</html>