<?= $this->doctype() ?>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php // $this->headTitle('SisRes | Login ')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?=
        $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?=
        $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('vendors/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('vendors/nprogress/nprogress.css'))
                ->prependStylesheet($this->basePath('vendors/animate.css/animate.min.css'))
                ->prependStylesheet($this->basePath('build/css/custom.min.css'))
                ->prependStylesheet($this->basePath('vendors/bootstrap/dist/css/bootstrap.min.css'))
    ?>
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <div class="animate form login_form">
            <section class="login_content">
                <form method="POST">
                    <h1>Login</h1>
                    <div>
                        <input type="text" name="usuario" class="form-control" placeholder="Usuario" required />
                    </div>
                    <div>
                        <input type="password" name="clave" class="form-control" placeholder="Clave" required />
                    </div>
                    <div>
                        <button class="btn btn-default submit">Ingresar</button>
                        <a class="reset_pass" href="#">Olvidaste tu clave?</a>
                    </div>

                    <div class="clearfix"></div>

                    <div class="separator">
      <!--                <p class="change_link">New to site?
                        <a href="#signup" class="to_register"> Create Account </a>
                      </p>-->

                        <div class="clearfix"></div>
                        <br />

                        <div>
                            <h1><i class="fa fa-globe"></i> <?= \Negocio\Configuracion::Empresa ?></h1>
                            <p>©<?= date('Y') ?> Todos los Derechos Reservados</p>
                        </div>
                    </div>
                </form>
            </section>
        </div>
      </div>
    </div>
  </body>
</html>