<?php
$title = $this->titulo;
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><?= $title ?></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><button type="button" id="btn-manual" class="btn btn-info" data-toggle="modal" data-target="#pasajeroModal">
                            <span class="glyphicon glyphicon-user text-white" aria-hidden="true"></span>
                            Agregar Manual
                        </button></li>
                        <li><button type="button" id="btn-excel" class="btn btn-success" data-toggle="modal" data-target="#excelModal">
                            <span class="glyphicon glyphicon-open-file text-white" aria-hidden="true"></span>
                            Agregar Excel</button></li>
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">

                <p>Simple table with project listing with progress and editing options</p>

                <!-- start project list -->
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">#</th>
                            <th style="width: 20%">Project Name</th>
                            <th>Team Members</th>
                            <th>Project Progress</th>
                            <th>Status</th>
                            <th style="width: 20%">#Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="57" aria-valuenow="56" style="width: 57%;"></div>
                                </div>
                                <small>57% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="47" aria-valuenow="46" style="width: 47%;"></div>
                                </div>
                                <small>47% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="77" aria-valuenow="76" style="width: 77%;"></div>
                                </div>
                                <small>77% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="60" aria-valuenow="59" style="width: 60%;"></div>
                                </div>
                                <small>60% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="12" aria-valuenow="11" style="width: 12%;"></div>
                                </div>
                                <small>12% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="35" aria-valuenow="34" style="width: 35%;"></div>
                                </div>
                                <small>35% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="87" aria-valuenow="86" style="width: 87%;"></div>
                                </div>
                                <small>87% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="77" aria-valuenow="76" style="width: 77%;"></div>
                                </div>
                                <small>77% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                        <tr>
                            <td>#</td>
                            <td>
                                <a>Pesamakini Backend UI</a>
                                <br>
                                <small>Created 01.01.2015</small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                    <li>
                                        <img src="/images/user.png" class="avatar" alt="Avatar">
                                    </li>
                                </ul>
                            </td>
                            <td class="project_progress">
                                <div class="progress progress_sm">
                                    <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="77" aria-valuenow="76" style="width: 77%;"></div>
                                </div>
                                <small>77% Complete</small>
                            </td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs">Success</button>
                            </td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
                                <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <!-- end project list -->

            </div>
        </div>
    </div>
</div>
<!-- Modal Excel  -->
<div class="modal fade" id="excelModal" tabindex="-1" role="dialog" aria-labelledby="excelModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Agregar Pasajeros</h4>
      </div>
      <div class="modal-body">
          <span>
              
          </span>
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
<!-- Modal Pasajeros  -->
<div class="modal fade" id="pasajeroModal" tabindex="-1" role="dialog" aria-labelledby="pasajeroModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>