-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 21:46:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(300) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_documento` ;

CREATE TABLE IF NOT EXISTS `tipo_documento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `abreviacion` VARCHAR(5) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nacionalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nacionalidad` ;

CREATE TABLE IF NOT EXISTS `nacionalidad` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pasajero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasajero` ;

CREATE TABLE IF NOT EXISTS `pasajero` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_documento_id` INT NOT NULL COMMENT '',
  `numero_documento` VARCHAR(12) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellidos` VARCHAR(200) NULL COMMENT '',
  `correo` VARCHAR(100) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `celular` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `nacionalidad` VARCHAR(45) NULL COMMENT '',
  `fecha_nacimiento` DATE NULL COMMENT '',
  `nacionalidad_id` INT NOT NULL COMMENT '',
  UNIQUE INDEX `numero_documento_UNIQUE` (`numero_documento` ASC)  COMMENT '',
  INDEX `fk_pasajero_tipo_documento1_idx` (`tipo_documento_id` ASC)  COMMENT '',
  UNIQUE INDEX `tipo_documento_id_UNIQUE` (`tipo_documento_id` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_pasajero_nacionalidad1_idx` (`nacionalidad_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pasajero_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasajero_nacionalidad1`
    FOREIGN KEY (`nacionalidad_id`)
    REFERENCES `nacionalidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(40) NULL COMMENT '',
  `password` VARCHAR(40) NULL COMMENT '',
  `full_name` VARCHAR(300) NULL COMMENT '',
  `email` VARCHAR(300) NULL COMMENT '',
  `active` INT(1) NULL COMMENT '',
  `role_id` INT NOT NULL COMMENT '',
  `pasajero_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_user_role_idx` (`role_id` ASC)  COMMENT '',
  INDEX `fk_user_pasajero1_idx` (`pasajero_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_pasajero1`
    FOREIGN KEY (`pasajero_id`)
    REFERENCES `pasajero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `menu` ;

CREATE TABLE IF NOT EXISTS `menu` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `module` VARCHAR(100) NULL COMMENT '',
  `controller` VARCHAR(100) NULL COMMENT '',
  `action` VARCHAR(100) NULL COMMENT '',
  `label` VARCHAR(150) NULL COMMENT '',
  `parent` INT(11) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `idmenu_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `privilege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `privilege` ;

CREATE TABLE IF NOT EXISTS `privilege` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `role_id` INT NOT NULL COMMENT '',
  `menu_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_privilege_role1_idx` (`role_id` ASC)  COMMENT '',
  INDEX `fk_privilege_menu1_idx` (`menu_id` ASC)  COMMENT '',
  CONSTRAINT `fk_privilege_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_privilege_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colegio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio` ;

CREATE TABLE IF NOT EXISTS `colegio` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `pagina_web` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `telefono_2` VARCHAR(45) NULL COMMENT '',
  `contacto` VARCHAR(45) NULL COMMENT '',
  `telefono_contacto` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria` ;

CREATE TABLE IF NOT EXISTS `categoria` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salon` ;

CREATE TABLE IF NOT EXISTS `salon` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nivel` VARCHAR(1) NULL COMMENT '',
  `grado` VARCHAR(1) NULL COMMENT '',
  `seccion` VARCHAR(1) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `colegio_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_Salon_colegio1_idx` (`colegio_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Salon_colegio1`
    FOREIGN KEY (`colegio_id`)
    REFERENCES `colegio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco` ;

CREATE TABLE IF NOT EXISTS `banco` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cta_bancaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cta_bancaria` ;

CREATE TABLE IF NOT EXISTS `cta_bancaria` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nro_cta` VARCHAR(100) NULL COMMENT '',
  `banco_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_cta_bancaria_banco1_idx` (`banco_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cta_bancaria_banco1`
    FOREIGN KEY (`banco_id`)
    REFERENCES `banco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneda` ;

CREATE TABLE IF NOT EXISTS `moneda` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `simbolo` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paquete_turistico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paquete_turistico` ;

CREATE TABLE IF NOT EXISTS `paquete_turistico` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `titulo` VARCHAR(200) NULL COMMENT '',
  `fecha_viaje` DATE NULL COMMENT '',
  `destino` VARCHAR(100) NULL COMMENT '',
  `precio_viaje` DECIMAL(10,0) NULL COMMENT '',
  `salon_id` INT NOT NULL COMMENT '',
  `documento_adicional` VARCHAR(1) NULL COMMENT '',
  `cta_bancaria_id` INT NOT NULL COMMENT '',
  `moneda_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_paquete_turistico_salon1_idx` (`salon_id` ASC)  COMMENT '',
  INDEX `fk_paquete_turistico_cta_bancaria1_idx` (`cta_bancaria_id` ASC)  COMMENT '',
  INDEX `fk_paquete_turistico_moneda1_idx` (`moneda_id` ASC)  COMMENT '',
  CONSTRAINT `fk_paquete_turistico_salon1`
    FOREIGN KEY (`salon_id`)
    REFERENCES `salon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquete_turistico_cta_bancaria1`
    FOREIGN KEY (`cta_bancaria_id`)
    REFERENCES `cta_bancaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paquete_turistico_moneda1`
    FOREIGN KEY (`moneda_id`)
    REFERENCES `moneda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cobro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cobro` ;

CREATE TABLE IF NOT EXISTS `cobro` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `monto_pendiente` DECIMAL(10,0) NOT NULL COMMENT '',
  `paquete_turistico_id` INT NOT NULL COMMENT '',
  `descuento` DECIMAL(10,0) NULL COMMENT '',
  `pasajero_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_cobro_paquete_turistico1_idx` (`paquete_turistico_id` ASC)  COMMENT '',
  INDEX `fk_cobro_pasajero1_idx` (`pasajero_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cobro_paquete_turistico1`
    FOREIGN KEY (`paquete_turistico_id`)
    REFERENCES `paquete_turistico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cobro_pasajero1`
    FOREIGN KEY (`pasajero_id`)
    REFERENCES `pasajero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pago` ;

CREATE TABLE IF NOT EXISTS `pago` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cobro_id` INT NOT NULL COMMENT '',
  `fecha_pago` DATE NULL COMMENT '',
  `forma_pago` VARCHAR(1) NULL COMMENT '1: Pago Caja Efectivo\n2: Pago Caja POS\n3: Deposito Bancario',
  `tipo_tarjeta` VARCHAR(45) NULL COMMENT '',
  `nombre_banco` VARCHAR(45) NULL COMMENT '',
  `fecha_transaccion` VARCHAR(45) NULL COMMENT '',
  `codigo_banco` VARCHAR(3) NULL COMMENT '',
  `pasajero_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_pago_cobro1_idx` (`cobro_id` ASC)  COMMENT '',
  INDEX `fk_pago_pasajero1_idx` (`pasajero_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pago_cobro1`
    FOREIGN KEY (`cobro_id`)
    REFERENCES `cobro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_pasajero1`
    FOREIGN KEY (`pasajero_id`)
    REFERENCES `pasajero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voucher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `voucher` ;

CREATE TABLE IF NOT EXISTS `voucher` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo_operacion` VARCHAR(45) NULL COMMENT '',
  `fecha_pago` DATE NULL COMMENT '',
  `fecha_transaccion` DATE NULL COMMENT '',
  `codigo_banco` VARCHAR(3) NULL COMMENT '',
  `monto` DECIMAL(10,0) NULL COMMENT '',
  `estado` VARCHAR(1) NULL COMMENT '0 = pendiente\n1= procesado\n2 = anulado',
  `img` BLOB NULL COMMENT '',
  `usuario_aud` VARCHAR(45) NULL COMMENT '',
  `user_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_voucher_user1_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_voucher_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
