<?php

$title = $this->titulo;
$this->headTitle($title);

$form = $this->form;
//$form->setAttribute('action', $this->url());
$form->setAttribute('class', 'form-horizontal form-label-left');

$isEdit = (!empty($this->isEdit) ? true : false);
$btnDsc = (!empty($isEdit) ? 'Grabar' : 'Grabar');
$campos = $this->campos;
$descripciones = $this->camposDescripcion;

foreach ($campos as $keyField => $field) {
    $showField = false;

    if ((((empty($field['AI']) || $field['AI'] == 0) && !$isEdit) || $isEdit) && empty($field['FK'])) {
        $form->add([
            'name' => $keyField,
            'type' => 'text',
            'attributes' => [
                'class' => 'form-control col-md-12 col-xs-12 ' . (!empty($field['DATE']) ? 'date-picker' : ''),
                'maxlength' => (!empty($field['LENGHT']) ? $field['LENGHT'] : null),
                'required' => 'required',
                'value' => (!empty($this->defaultValue[$keyField]) ? $this->defaultValue[$keyField] : ''),
                'placeholder' => 'Inserte aquí',
                'readonly' => (!empty($field['PK']) ? $field['PK'] : ''),
            ],
            'options' => [
                'label' => $descripciones[$keyField],
                'label_attributes' => array(
                    'class' => 'control-label col-md-5 col-sm-5 col-xs-5',
                ),
            ],
        ]);

        $showField = true;
    }

    if (!empty($field['FK'])) {
        $form->add([
            'name' => $keyField,
            'type' => 'select',
            'attributes' => [
                'class' => 'form-control col-md-12 col-xs-12',
                'required' => 'required',
                'value' => (!empty($this->defaultValue[$keyField]) ? $this->defaultValue[$keyField] : ''),
            ],
            'options' => [
                'label' => $descripciones[$keyField],
                'label_attributes' => array(
                    'class' => 'text-danger control-label col-md-5 col-sm-5 col-xs-5',
                ),
                'value_options' => !empty($field['FUNC']) ? $this->fk[$field['FUNC']] : []
            ],
        ]);

        $showField = true;
    }

    if ($showField) {
        $formFields[] = $form->get($keyField);
    }
}

$element = new \Zend\Form\Element('reset');
$element->setAttribute('class', 'btn btn-primary');
$element->setAttribute('value', 'Cancelar');

$form->add($element);
$form->add([
    'type' => 'submit',
    'name' => 'submit',
    'attributes' => [
        'class' => 'btn btn-success',
        'value' => $btnDsc,
    ],
]);
$submit = $form->get('submit');
$reset = $form->get('reset');

$form->prepare();
?>
<div style="margin-left: 200px;">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-body">
                <div class="form-validation">
                    <div class="x_content">
                        <div class="row">
                            <div style="margin-left: 45px;">
                                <div class="title_left">
                                    <h1 class="card-title"><?= $this->escapeHtml($title); ?></h1>
                                    <h2 class="card-subtitle">Agregar</h2>
                                </div>
                            </div>
                        </div>
                        <br>
                        <?= $this->form()->openTag($form); ?>
                        <?php foreach ($formFields as $field): ?>
                            <div class="form-group row">
                                <?= $this->formLabel($field) ?>
                                <div class="col-md-7 col-sm-7 col-xs-7">
                                    <?= $this->formElement($field) ?>
                                    <?= $this->formElementErrors()->render($field, ['class' => 'help-block']) ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                        <div style="margin-left: 150px;">
                            <div class="form-group row">
                                <div class="col-md-9 col-sm-9 col-xs-9 col-md-offset-3">
                                <?= $this->formSubmit($submit); ?>
                                <?= $this->formReset($reset); ?>
                                </div>
                            </div>
                        </div>
                        <?php
                        echo $this->form()->closeTag();
                        ?>
                </div>
            </div>
        </div>
    </div>
</div>


