<h1>Agregar</h1>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url());

$campos = $this->campos;
$descripciones = $this->camposDescripcion;
foreach ($campos as $keyField => $field) {
    if (empty($field['AI']) || $field['AI'] == 0) {
        
        $form->add([
            'name' => $keyField,
            'type' => 'text',
            'options' => [
                'label' => $descripciones[$keyField],
            ],
        ]);
/*
        $fieldset = $form->get($keyField);

        $formField = $fieldset->get($keyField);
        $formField->setAttribute('class', 'form-control');
        $formField->setAttribute('placeholder', $descripciones[$keyField]);
        $formField->setAttribute('maxlength', $field['LENGHT']);
        if (!empty($field['PK']) && $field['PK'] == 1) {
            $formField->setAttribute('required', 'required');
        }
   */      
        $formFields[] = $form->get($keyField);
 

    }
}

//$submit = $form->get('submit');
//$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>
<fieldset>
    <?php foreach ($formFields as $field): ?>
    <div class="form-group">
        <?= $this->formLabel($field) ?>
        <?= $this->formElement($field) ?>
        <?= $this->formElementErrors()->render($field, ['class' => 'help-block']) ?>
    </div>
    <?php    endforeach; ?>
</fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();