<?php
// module/Album/view/album/album/delete.phtml:

$title = $this->titulo;
$url   = ''/*$this->url('album', ['action' => 'delete', 'id' => $id])*/;

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Esta seguro de eliminar el registro de 
    <?= $this->escapeHtml($this->dscItemEliminar) ?>?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <?php
        $campos = $this->campos;
        if (!empty($campos)) {
            foreach ($campos as $keyField => $field) {
                if (!empty($field['PK'])) {
    ?>
        <input type="hidden" name="<?= $keyField ?>" value="<?= $this->defaultValue[$keyField] ?>" />
    <?php
                }
            }
        }
    ?>
    <input type="submit" class="btn btn-danger" name="del" value="Si" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>