<?php 
$title = $this->titulo;
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?= $this->url($this->urlPrefix . 'agregar') ?>">Agregar nuevo</a>
</p>

<table class="table">
    <tr>
        <?php foreach ($this->columnas as $id => $cabecera) { ?>
            <th><?= $cabecera; ?></th>
        <?php } ?>
        <th>&nbsp;</th>
    </tr>
    <?php if ($this->paginator->getTotalItemCount() > 0) { ?>
        <?php foreach ($this->paginator as $fila) : // <-- change here! ?>
            <tr>
                <?php foreach ($this->columnas as $id => $cabecera) { ?>
                    <td><?= $this->escapeHtml($fila->$id) ?></td>
                <?php } ?>
                <td>
                    <a href="<?= $this->url($this->urlPrefix . 'editar', ['id' => $fila->id]) ?>">Edit</a>
                    <a href="<?= $this->url($this->urlPrefix . 'eliminar', ['id' => $fila->id]) ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php } else { ?>
            <tr>
                <td colspan="<?= count($this->columnas) + 1 ?>">No se encontró información</td>
            </tr>
    <?php } ?>
</table>