<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
   <?=
   $this->headMeta()
      ->appendName('viewport', 'width=device-width, initial-scale=1.0')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
   ?>
    <!-- Favicon icon -->
    <?= $this->headTitle(\Business\Settings::BusinessName . ' | Login ')->setSeparator(' - ')->setAutoEscape(false) ?>

   <?=
   $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'])
      ->prependStylesheet($this->basePath('css/lib/bootstrap/bootstrap.min.css'))
      ->prependStylesheet($this->basePath('css/helper.css'))
      ->prependStylesheet($this->basePath('css/style.css'))
   ?>
</head>
<body class="fix-header fix-sidebar">
<!-- Preloader - style you can find in spinners.css -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
</div>
<!-- Main wrapper  -->
<div id="main-wrapper">
    <div class="unix-login">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-4">
                    <div class="login-content card">
                        <div class="login-form">
                            <h4>Login</h4>
                            <form method="POST">
                                <div class="form-group">
                                    <label>Usuario</label>
                                    <input name="usuario" class="form-control" placeholder="Usuario">
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" name="clave" class="form-control" placeholder="Password">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox"> Remember Me
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Sign in</button>
                                <div class="register-link m-t-15 text-center">
                                    <h2><i class="fa fa-globe"></i> <?= \Business\Settings::BusinessName ?></h2>
                                    <small>©<?= date('Y') ?> Todos los Derechos Reservados</small>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Scripts -->
<?=
$this->headScript()
   ->appendFile($this->basePath('js/lib/jquery/jquery.min.js'))
   ->appendFile($this->basePath('js/lib/bootstrap/js/popper.min.js'))
   ->appendFile($this->basePath('js/lib/bootstrap/js/bootstrap.min.js'))
   ->appendFile($this->basePath('js/jquery.slimscroll.js'))
   ->appendFile($this->basePath('js/sidebarmenu.js'))
   ->appendFile($this->basePath('js/lib/sticky-kit-master/dist/sticky-kit.min.js'))
   ->appendFile($this->basePath('js/custom.min.js'))
?>
<?php $this->FlashMsg(); ?>
<?= $this->inlineScript() ?>
</body>
</html>